MBIT/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('form/', views.form, name='form'),
    path('submit/', views.submit, name='submit'),
    path('result/<int:developer_id>', views.result, name='result'),
    path('all_results/', views.all_results, name='all_results'),
]

main/models.py
from django.db import models

class Developer(models.Model):
    name = models.CharField(max_length=50)
    count = models.IntegerField(default=0)
    data = models.JSONField()
    
    def __str__(self):
        return self.name
    
class Question(models.Model):
    number = models.IntegerField(unique=True)
    content = models.CharField(max_length=100)
    
    def __str__(self):
        return f'{self.number}. {self.content}'
    
class Choice(models.Model):
    content = models.CharField(max_length=100)
    question = models.ForeignKey(to='main.Question', 
                                 on_delete=models.CASCADE)
    developer = models.ForeignKey(to='main.Developer', 
                                  on_delete=models.CASCADE,
                                 null=True)
    
    def __str__(self):
        return self.content

main/views.py
from django.shortcuts import render, redirect
from .models import Question, Developer, Choice

def index(request):
    developers = Developer.objects.all()
    
    context = {
        'developers' : developers,
        
    }
    
    return render(request, 'main/index.html', context=context)

def form(request):
    questions = Question.objects.all()
    
    context = {
        'questions' : questions,
        
    }
    
    return render(request, 'main/form.html', context=context)

def submit(request):
   #문항 수
    N = Question.objects.count()
    # 개발자 유형의 수
    K = Developer.objects.count()
    #print(f'문항 수 : {N}, 개발자 유형 수 : {K}')
    
    counter = [0] * (K+1)
    
    #print(f'POST : {request.POST}')
    for n in range(1, N+1):
        developer_id = int(request.POST[f'question-{n}'][0])
        counter[developer_id] += 1
        
    #최고점 개발 유형
    best_developer_id = max(range(1, K+1), key=lambda id : counter[id]) #최대값 
    best_developer = Developer.objects.get(pk= best_developer_id)
    best_developer.count += 1
    best_developer.save()
    
    context = {
        'developer' : best_developer,
        'counter' : counter
    }
    return redirect('main:result', developer_id=best_developer_id)

def result(request, developer_id):
    developer = Developer.objects.get(pk=developer_id)
    context = {
        'developer' : developer,
    }
    return render(request, 'main/result.html', context)

def all_results(request):
    return render(request, 'main/all_results.html')

main/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% block head %}
  {% endblock head %}
  <title>나의 제주 여행 - final</title>
</head>
<body>
  {% block body %}
  {% endblock body %}

  {% block js %}
  {% endblock js %}
</body>
</html>

main/templates/main/form.html
{% extends 'main/base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/form.css' %}">
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
{% endblock head %}

{% block body %}
    <section id="survey">
        <div class="wrapper">
            <form id="form" action="{% url 'main:submit' %}" method="post">
                {% csrf_token %}
                {% for question in questions %}
                    <div class="test">
                        <div class="question_container">
                            <h3 class="number">{{ question.number }}/{{ questions.count }}</h3>
                            <h3 class="question">{{ question.content }}</h3>
                        </div>
                        <div class="answer">
                          {% for choice in question.choice_set.all %}
                            <div>
                              <input 
                                type="radio" 
                                name="question-{{ question.number }}" 
                                id="choice-{{ choice.pk }}" 
                                value="{{ choice.developer.pk }}"
                              />
                              <label for="choice-{{ choice.pk }}">{{ choice.content }}</label>
                            </div>
                          {% endfor %}
                        </div>
                        {% if not forloop.first %}
                        <div class="btn_wrap btn_sort">
                        {% else %}
                        <div class="btn_wrap">
                        {% endif %}
                        {% if not forloop.first %}
                            <button class="prev_btn">이전</button>
                        {% endif %}
                        {% if not forloop.last %}
                            <button class="next_btn">다음</button>
                        {% else %}
                            <input type="submit" value="제출" class="submit_btn"/>
                        {% endif %}
                        </div>
                        </div>
                {% endfor %}
                </div>
            </form>
        </div>
    </section>
{% endblock body %}

{% block js %}
        <script type="text/javascript" src="{% static 'js/form.js' %}"></script>
{% endblock js %}

main/templates/main/form_back.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
    <form action="/result/" method='post'>
        {% csrf_token %}
        {% for question in questions %}
            <h3> {{ question.number}}번 : {{ question.content}} </h3>
            {% for choice in question.choice_set.all %}
                <div>
                    <input type="radio" name="question-{{question.pk}}" id="choice-{{choice.pk}}" value="{{choice.developer.pk}}">
                    <label for="choice-{{choice.pk}}">{{ forloop.counter }}. {{choice.content}}</label>
                    
                </div>
            {% endfor %}
        <hr>
        {% endfor %}
        <input type="submit" value="제출하기">
    </form>
</body>
</html>

main/templates/main/index.html
{% extends 'main/base.html' %}
{% load static %}

{% block head %}
    
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
{% endblock head %}

{% block body %}
    <section id="main_contents">
        <div class="wrapper">
            <div class="title">
                <!--h3.sub_title 치고 enter-->
                <h3 class="main_title">나의 제주여행</h3>
                <!--<h3 class="sub_title">My trip to Jeju island</h3>-->
            </div>
            <div class="intro">
                <h1>어디로 떠나볼까?!</h1>
                <div class="type">
                    <ul class="type_list">
                        <li>비자림</li>
                        <li>메이즈랜드</li>
                        <li>성읍민속마을</li>
                        <li>9.81파크</li>
                        <li>비자림</li>
                    </ul>
                </div>
            </div>
            <div class="button">
                <a href="{% url 'main:form' %}">
                    <button class="start" type="button">시작하기</button>
                </a>
            </div>
        </div>
    </section>
{% endblock body %}

main/templates/main/index_back.html
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Document</title>
    </head>
    <body>
        <h1> hello world </h1>
        <p> hello </p>

        {% for developer in developers %}
            <p> {{ developer.name}} : {{ developer.count}} </p>
        {% endfor %}
    </body>
    </html>

main/templates/main/result.html
{% extends 'main/base.html' %}
{% load static %}

{% block head %}
    <meta property="og:title" content="나의 개발 유형은?" />
    <meta property="og:image" content="" />
    <meta property="og:url" content="" />
    <meta property="og:description" content="나에게 꼭 맞는 개발 유형은 무엇일까?" />

    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/result.css' %}">
{% endblock head %}

{% block body %}
    <section id="main_contents">
        <div class="wrapper">
            <div class="result">
                <div class="titles">
                    <h3>{{ developer.data.title }}</h3>
                    <h1>{{ developer.name }}</h1>
                </div>
                <class class="result_img">
                    <img src="{% static 'img/' %}{{ developer.pk }}.png" width="300"/>
                </class>
            </div>
            <div class="result_explains">
                <div class="explain">
                    <h3 class="title">나와 맞는 여행지는 {{ developer.data.imageonename }}?!</h3>
                    <class class="result_img">
                        <img src="{% static '' %}{{ developer.data.imageone }}" width='200px' alt="{{ developer.data.imageonename }}">
                    </class>
                    <ul>
                        {% for feature in developer.data.features %}
                        <li>
                            {{ feature }}
                        </li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="explain">
                    <h3 class="title">나와 맞는 여행지는 {{ developer.data.imagestwoname }}?!</h3>
                    <class class="result_img">
                        <img src="{% static '' %}{{ developer.data.imagestwo }}" width='200px' alt="{{ developer.data.imagestwoname }}">
                    </class>
                    <ul>
                        {% for description in developer.data.descriptions %}
                        <li>
                            {{ description }}
                        </li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="explain">
                    <h3 class="title">나와 맞는 여행지는 {{ developer.data.imagesthreename }}?!</h3>
                    <class class="result_img">
                        <img src="{% static '' %}{{ developer.data.imagesthree }}" width='200px' alt="{{ developer.data.imagesthreename }}">
                    </class>
                    <ul>
                        {% for explanation in developer.data.explanations %}
                        <li>
                            {{ explanation }}
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            <div class="lectures">
                <h3 class="title">사이트</h3>
                <p>더 많은 정보를 원하시나요?</p>
                <ul>
                    <li>
                        <a href="https://www.visitjeju.net/kr" target="_blank">
                                <img src="{% static 'image/visitjeju_logo.png' %}" alt="비짓제주">
                                <h3>visitjeju</h3>
                                <button type="button">사이트 방문하기</button>
                        </a>
                    </li>
                </ul>
            </div>
            <div class="share">
                <div class="url">
                    <button class="copy_btn" type="button">URL 복사하기</button>
                </div>
                <div class="facebok">
                    <button class="facebook_share" type="button">Facebook 공유하기</button>
                </div>
                <div class="kakao">
                    <button class="kakao_share" type="button">카카오톡 공유하기</button>
                </div>
            </div>
            <div class="buttons">
                <ul>
                    <li>
                        <h3>...이건 내가 아니야... 잘못된게 분명해!</h3>
                        <a href="{% url 'main:index' %}">
                            <button type="button">테스트 다시하기</button>
                        </a>
                    </li>
                <!--
                    <li>
                        <h3>다른 사람들은 어떤 유형일까?</h3>
                        <a href="{% url 'main:all_results' %}">
                            <button type="button">다른 결과 알아보기</button>
                        </a>
                    </li>
                -->
                    <li>
                        <h3>이런 테스트는 도대체 누가 만든거야?</h3>
                        <a href="">
                            <button class="color" type="button">하은유</button>
                        </a>
                    </li>
                </ul>
            </div>
            <div class="weniv">
                <a href="http://www.paullab.co.kr">
                    <img src="{% static 'image/visitjeju_logo.png' %}" alt="weniv">
                </a>
            <!--    
            </div>
            <p>※ 본 서비스 내 이미지 및 콘텐츠의 저작권은 주식회사 위니브에 있습니다.
                <br>
              수정 및 재배포, 무단 도용 시 법적인 문제가 발생할 수 있습니다.</p>
-->
            </div>
            </div>
        </div>
    </section>
{% endblock body %}

{% block js %}
    <script src="https://developers.kakao.com/sdk/js/kakao.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
    <script type="text/javascript" src="{% static 'js/result.js' %}"></script>
{% endblock js %}

main/templates/main/result_back.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
    <h1>결과페이지</h1>
    <p>{{ developer.name }}</p>
    <img src="{% static 'image/' %}{{ developer.pk }}.png" width="300"/>
    <a href="/">메인화면</a>
    <a href="/form">다시하기</a>    
</body>
</html>